export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_PROFILE = "GET_PROFILE"

export const GET_SNAKE_GAME_INFO = "GET_SNAKE_GAME_INFO"
export const SEND_GAME_OVER_INFO = "SEND_GAME_OVER_INFO"
export const RESET_SNAKE_GAME_SCORE = "RESET_SNAKE_GAME_SCORE"
export const GET_RATING_TABLE_PAGE = "GET_RATING_TABLE_PAGE"